### ISSUE TITLE
Rmd

### ISSUE THREAD

**Issue by mdogucu** [rladies/meetup-presentations_sarasota#2]
@CatherineH Should we make the presentation in an R Markdown file since GitHub can display Markdown files?

**Comment by CatherineH** [comment]
Sure, I'm just not sure what the difference between .Rpress and R markdown is.

**Comment by mdogucu** [comment]
I moved everything to .Rmd. format. But the screenshots got messed up. I have everything ready except for few of you first slides.  You should be able to see the difference pretty easily. 

Also, when you pull to your local machine if you click on the meetup-presentations_sarasota.Rproj file to open in RStudio, your working directory and everything else would load by default so you do not have to include long file paths. It is especially neat when collaborating so each of us do not have to change file paths. Projects are awesome, that is why I added a slide about them.

Thanks @CatherineH. See you soon!

**Comment by mdogucu** [comment]
Has been resolved long time ago
